version: '3'

tasks:
  run:
    watch: true
    cmds:
      - go build -o bin/main cmd/main.go
      - defer: rm bin/main
      - bin/main
    sources:
      - '**/*.go'
    generates:
      - './bin/main'

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'
