version: '3'

dotenv: ['.env']

interval: 500ms

tasks:
  taskapp_build:
    cmds:
      - go build -o bin/taskapp cmd/taskapp/main.go
    generates:
      - './bin/taskapp'
    sources:
      - 'cmd/taskapp/*.go'
      - 'pkg/**/*.go'

  api:
    watch: true
    cmds:
      - task: taskapp_build
      - bin/taskapp api

  seed:
    cmds:
      - task: taskapp_build
      - bin/taskapp seed

  agendas:
    cmds:
      - task: taskapp_build
      - bin/taskapp agendas

  db:
    cmds:
      - docker compose -f docker/docker-compose.yml up db

  db_admin:
    cmds:
      - docker compose -f docker/docker-compose.yml up db_admin

  tui_build:
    cmds:
      - go build -o bin/tui cmd/tui/main.go
    generates:
      - './bin/tui'
    sources:
      - 'cmd/tui/*.go'
      - 'tui/**/*.go'
      - 'pkg/**/*.go'

  tui:
    env:
      DEBUG: 1
    cmds:
      - task: tui_build
      - bin/tui

  tui_log:
    cmds:
      - rm -f debug.log
      - touch debug.log
      - tail -f debug.log

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'


