version: '3'

interval: 500ms
tasks:
  api:
    watch: true
    cmds:
      - go build -o bin/server cmd/server/main.go
      - defer: rm bin/server
      - bin/server
    sources:
      - 'cmd/server/*.go'
      - 'pkg/**/*.go'
    generates:
      - './bin/server'

  seed:
    cmds:
      - go build -o bin/seed cmd/seed/main.go
      - defer: rm bin/seed
      - bin/seed

  db:
    cmds:
      - docker-compose -f docker/docker-compose.yml up db

  db_admin:
    cmds:
      - docker-compose -f docker/docker-compose.yml up db_admin

  tui:
    env:
      DEBUG: 1
    cmds:
      - go build -o bin/tui cmd/tui/main.go
      - defer: rm bin/tui
      - bin/tui

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'


