version: '3'

interval: 500ms
tasks:
  dev:
    watch: true
    cmds:
      - go build -o bin/server cmd/server/main.go
      - defer: rm bin/server
      - bin/server
    sources:
      - 'cmd/server/*.go'
      - 'pkg/**/*.go'
    generates:
      - './bin/server'

  tui:
    cmds:
      - go build -o bin/tui cmd/tui/main.go
      - defer: rm bin/tui
      - bin/tui
  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'

  db:
    cmds:
      - docker-compose -f docker/docker-compose.yml up db
