version: '3'

interval: 500ms
tasks:
  api_build:
    cmds:
      - go build -o bin/server cmd/server/main.go
    generates:
      - './bin/server'
    sources:
      - 'cmd/server/*.go'
      - 'pkg/**/*.go'

  api:
    watch: true
    cmds:
      - task: api_build
      - bin/server

  seed_build:
    cmds:
      - go build -o bin/seed cmd/seed/main.go
    generates:
      - './bin/seed'
    sources:
      - 'cmd/seed/*.go'
      - 'pkg/**/*.go'

  seed:
    cmds:
      - task: seed_build
      - bin/seed

  agendas_build:
    cmds:
      - go build -o bin/agendas cmd/agendas/main.go
    generates:
      - './bin/agendas'
    sources:
      - 'cmd/agendas/*.go'
      - 'pkg/**/*.go'

  agendas:
    cmds:
      - task: agendas_build
      - bin/agendas

  db:
    cmds:
      - docker compose -f docker/docker-compose.yml up db

  db_admin:
    cmds:
      - docker compose -f docker/docker-compose.yml up db_admin

  tui_build:
    cmds:
      - go build -o bin/tui cmd/tui/main.go
    generates:
      - './bin/tui'
    sources:
      - 'cmd/tui/*.go'
      - 'tui/**/*.go'
      - 'pkg/**/*.go'

  tui:
    env:
      DEBUG: 1
    cmds:
      - task: tui_build
      - bin/tui

  tui_log:
    cmds:
      - tail -f debug.log

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'


