version: '3'

dotenv: ['.env']

interval: 500ms

tasks:
  build:
    cmds:
      - go build -o bin/soq cmd/main.go
    generates:
      - './bin/soq'
    sources:
      - 'cmd/*.go'
      - 'api/**/*.go'
      - 'pkg/**/*.go'

  api:
    watch: true
    cmds:
      - task: build
      - bin/soq api

  seed:
    cmds:
      - task: build
      - bin/soq seed

  agendas:
    cmds:
      - task: build
      - bin/soq agendas

  db:
    cmds:
      - docker compose -f docker/docker-compose.yml up db

  db_admin:
    cmds:
      - open http://localhost:5444/
      - docker compose -f docker/docker-compose.yml up db_admin

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'


