name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  taskapp_build:
    name: Build taskapp Command
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup go-task
      uses: pnorton5432/setup-task@v1

    - name: Build
      run: task taskapp_build

  tui_build:
    name: Build Terminal UI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup go-task
      uses: pnorton5432/setup-task@v1

    - name: Build
      run: task tui_build

