name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      tag: ${{ steps.semver.outputs.next }}
      bump: ${{ steps.semver.outputs.bump }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Tag
        if: steps.semver.outputs.bump != 'none'
        run: |
          git config --global user.email "ci@tennyson.io"
          git config --global user.name "Github Actions"

          git remote add other https://${{ secrets.GITHUB_TOKEN }}@github.com/mole-squad/soq-api.git

          git tag -a ${{ steps.semver.outputs.next }} -m "${{ steps.semver.outputs.next }}"
          git push other --tags

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: ${{ needs.tag.outputs.bump != 'none' }}

    env:
      VERSION: ${{ needs.tag.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.VERSION }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ env.VERSION }} [skip ci]'
          file_pattern: CHANGELOG.md

  deploy:
    runs-on: ubuntu-latest

    if: ${{ needs.tag.outputs.bump != 'none' }}

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "qt2-task-app"
          heroku_email: "dev@tennyson.io"
          usedocker: true