name: Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      tag: ${{ steps.semver.outputs.next }}
      changes: ${{ steps.changelog.outputs.changes }}
      bump: ${{ steps.semver.outputs.bump }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Update CHANGELOG
        if: steps.semver.outputs.bump != 'none'
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}

      - name: Update version.txt
        if: steps.semver.outputs.bump != 'none'
        run: echo ${{ steps.semver.outputs.next }} > version.txt

      - name: Commit CHANGELOG.md and version.txt
        if: steps.semver.outputs.bump != 'none'
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: main
          commit_message: 'docs: ${{ steps.semver.outputs.next }} [skip ci]'
          file_pattern: CHANGELOG.md version.txt

  release:
    runs-on: ubuntu-latest

    needs: tag

    permissions:
      contents: write

    if: ${{ needs.tag.outputs.bump != 'none' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ needs.tag.outputs.tag }}
          name: ${{ needs.tag.outputs.tag }}
          body: ${{ needs.tag.outputs.changes }}
          token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest

    needs: tag

    if: ${{ needs.tag.outputs.bump != 'none' }}

    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "qt2-task-app"
          heroku_email: "dev@tennyson.io"
          usedocker: true