name: Tag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Tag
        if: steps.semver.outputs.bump != 'none'
        run: |
          git remote add other https://${{ secrets.GITHUB_TOKEN }}@github.com/molesquad/soq-api.git
          git tag -a ${{ steps.semver.outputs.next }}
          git push other --tags

