name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Tag
        if: steps.semver.outputs.bump != 'none'
        run: |
          git config --global user.email "ci@tennyson.io"
          git config --global user.name "Github Actions"

          git remote add other https://${{ secrets.GITHUB_TOKEN }}@github.com/mole-squad/soq-api.git

          git tag -a ${{ steps.semver.outputs.next }} -m "${{ steps.semver.outputs.next }}"
          git push other --tags

